#!/bin/bash
#
# docker autoprune unused docker/ volumes 
################################################################################
#sudo docker system prune -a -f
#sudo docker image prune -a -f
sudo docker system prune --volumes -a -f
