#!/bin/bash
#
# docker autoprune unused docker/ volumes 
################################################################################
#sudo docker system prune -a -f
docker image prune -a -f
docker system prune --volumes -a -f
