#!/bin/bash
#
# Title:      rclone updater
# GNU:        General Public License v3.0
################################################################################

rcversion="$(curl -s https://api.github.com/repos/rclone/rclone/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")')"
rcstored="$(tail -n 1 /var/plexguide/checkers/rclonestored.log)"
      tee <<-EOF

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 rClone Update Panel  			$rcstored
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

rclone installed version = 		$rcstored
rclone latest version 	 = 		$rcversion

[Y] UPDATE to lateste version

[Z] Exit
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
EOF

read -p 'Type  Y or Z | Press [ENTER]: ' typed </dev/tty


    case $typed in

    Y)
        ansible-playbook /opt/plexguide/menu/pg.yml --tags rcloneinstall
        bash /opt/plexguide/menu/pgui/templates/check.sh >/dev/null 2>&1
        ;;
    y)
        ansible-playbook /opt/plexguide/menu/pg.yml --tags rcloneinstall
        bash /opt/plexguide/menu/pgui/templates/check.sh >/dev/null 2>&1
        ;;
    z)
        exit
        ;;
    Z)
        exit
        ;;
esac
