#!/bin/bash
#
# Title:      rclone updater
# GNU:        General Public License v3.0
################################################################################

rcversion="$(curl -s https://api.github.com/repos/rclone/rclone/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")')"
touch /var/plexguide/checkers/rclonestored.log
touch /var/plexguide/checkers/rclone.log
rcstored="$(rclone --version | awk '{print $2}' | tail -n 3 | head -n 1 )"
echo "$rcstored" >> /var/plexguide/checkers/rclonestored.log

rcstored="$(tail -n 1 /var/plexguide/checkers/rclonestored.log)"

if [[ "$rcversion" == "$rcstored" ]]; then
        echo " ✅  No update needed !" >/var/plexguide/checkers/rclone.log
elif [[ "rcversion" != "rcstored" ]]; then
        echo " ⛔  Update possible !" >/var/plexguide/checkers/rclone.log
else echo "stupid line"
fi
rcupdate=$(tail -n 1 /var/plexguide/checkers/rclone.log)
      tee <<-EOF

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 rClone Update Panel  $rcupdate
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

rclone installed version = 		$rcstored
rclone latest version 	 = 		$rcversion

[1] UPDATE to lateste version

[Z] Exit
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
EOF

read -p 'Type a Number | Press [ENTER]: ' typed </dev/tty
  if [ "$typed" == "1" ]; then
	curl https://rclone.org/install.sh | sudo bash
  elif [ "$typed" == "Z" || "$typed" == "z" ]; then
  fi
