#!/bin/bash
#
# Title:      PGBlitz (Reference Title File)
# YML Author: Admin9705
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
# Origin:     https://github.com/l3uddz/plex_patrol
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    # FACTS ######################################################################
      #when: not config.stat.exists
    - name: Check Service's Existance
      stat:
        path: '/etc/systemd/system/plexpatrol.service'
      register: pgp

    - name: Stop service
      service:
        name: plexpatrol
        state: stopped
      when: pgp.stat.exists

    - name: Daemon-PTS-Patrol stop
      systemd: state=stopped name=plexpatrol daemon_reload=yes enabled=no

    - name: Remove Basic Directories
      file: 'path={{item}} state=absent mode=0775 owner=1000 group=1000'
      with_items:
        - '/opt/appdata/plexpatrol/'
        - '/etc/systemd/system/plexpatrol.service'
        - '/var/plexguide/plexpatrol'