#!/bin/bash
# Title:      ouroboros
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    # FACTS #######################################################################
    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'ouroboros'
    - name: 'Setting {{pgrole}} Volumes'
      set_fact:
        pg_volumes:
          - '/var/run/docker.sock:/var/run/docker.sock'
          - '/etc/localtime:/etc/localtime:ro'

    - name: 'Setting {{pgrole}} ENV'
      set_fact:
        pg_env:
          LATEST: 'true' #Some containers will break if set to latest, use tag already set by setting this to false
          CLEANUP: 'true'
          INTERVAL: '86400' #cEvery 24 hours in seconds
          LOG_LEVEL: 'info'
          SELF_UPDATE: 'true'
          MONITOR: '' #Can set to specific container only see wiki for details (https://github.com/pyouroboros/ouroboros/wiki/Usage#monitor)
          IGNORE: 'mariadb influxdb mongo postgres'
          LABELS_ONLY: 'false' #https://github.com/pyouroboros/ouroboros/wiki/Usage#label-enable
          LABEL_ENABLE: 'false'
 #         DATA_EXPORT: 'influxdb'
 #         INFLUX_URL: 'influxdb'
 #         INFLUX_PORT: '8086'
 #         INFLUX_USERNAME: 'admin'
 #         INFLUX_PASSWORD: 'adminpass'
 #         INFLUX_DATABASE: 'ouroboros'
 #         INFLUX_SSL: 'false'
 #         INFLUX_VERIFY_SSL 'false'
          NOTIFIERS: ''
          
    # MAIN DEPLOYMENT #############################################################
    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: 'pyouroboros/ouroboros'
        pull: yes
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        networks:
          - name: plexguide
            aliases:
              - 'ouroboros'
        state: started
