#!/bin/bash
#
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    # FACTS #######################################################################
    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'promtail'
        intport: '9080'
        extport: '9080'
        image: 'grafana/promtail'

    # CORE (MANDATORY) ############################################################
    - name: 'Including cron job'
      include_tasks: '/opt/plexguide/menu/new_ui/ymls/_core.yml'

    - name: 'Checking for existing {{pgrole}} config file'
      stat:
        path: '/opt/appdata/{{pgrole}}/docker-config.yaml'
      register: stat_result

    - name: 'Clone docker-config.yaml for first start'
      include_tasks: '/opt/plexguide/menu/new_ui/templates/promtail/promtail-conf.yml'
      when: stat_result.stat.exists == False
      ignore_errors: yes


    # LABELS ######################################################################

    - name: 'Setting {{pgrole}} Volumes'
      set_fact:
        pg_volumes:
          - '/opt/appdata/{{pgrole}}:/etc/promtail/'
          - '/etc/localtime:/etc/localtime:ro'
          - '/var/plexguide/logs:/var/log'

    - name: 'Setting {{pgrole}} ENV'
      set_fact:
        pg_env:
          PUID: '1000'
          PGID: '1000'

    # MAIN DEPLOYMENT #############################################################
    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}'
        pull: yes
        published_ports:
          - '{{ports.stdout}}{{extport}}:{{intport}}'
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        networks:
          - name: plexguide
            aliases:
              - '{{pgrole}}'       
        state: started

